version: '3.8'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.127.0
    container_name: cluster-pulse-otel-collector
    volumes:
      - ./observability/otel-collector/config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "8889:8889"

  prometheus:
    image: prom/prometheus:v3.11.3
    container_name: cluster-pulse-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/otel-collector/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:13.0.1-security-01
    container_name: cluster-pulse-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
